root: ./

​structure:  
    readme: README.md

redirects:
    umbraco-cms/fundamentals/setup/upgrading/general: umbraco-cms/fundamentals/setup/upgrading/README.md
    README: /umbraco-workflow/README.md 