root: ./

​structure:  
    readme: README.md

redirects:
    umbraco-cms/fundamentals/setup/upgrading/general: umbraco-cms/fundamentals/setup/upgrading/README.md
    README.md: https://docs.umbraco.com/umbraco-workflow/umbraco-workflow 